name: github-actions-ek8s-toolbox

on: [push]

jobs:
  github-actions-ek8s-toolbox:
    runs-on: ubuntu-latest
    name: github-actions-ek8s-toolbox
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build API Docker image
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mechtron/github-actions-ek8s-toolbox
          tag_with_ref: true
      - name: github-actions-ek8s-toolbox step
        id: github-actions-ek8s-toolbox
        uses: mechtron/github-actions-ek8s-toolbox@master
        with:
          eksClusterName: "example-cluster"
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsDefaultRegion: "us-east-1"
          helmVersion: "2.12.1"
          kubectlVersion: "1.13.9"
          istioctlVersion: "1.1.3"
          kubevalVersion: "0.14.0"
          command: |
            echo "Just a test ..."
            aws --version
            helm version
            kubectl version
            istioctl version
            kubeval --version
